[package]
name = "ark-ecfft"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.3.0"
ark-bn254 = "0.3.0"
ark-std = "0.3.0"
ark-poly = "0.3.0"